// <auto-generated />
namespace NewElevenNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedCategoryFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCategoryFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202104120320256_addedCategoryFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
